# Generated by Django 3.2.13 on 2023-07-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
    ]
